### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by hansfpc** [jenghis/nshift#4]

**Comment by Aupajo** [comment]
:+1: I tried opening the XCode project and ran *Build*. The build says “Succeeded”, and the Target's installation directory is set to `/usr/local/bin`, but the binary doesn't appear.

**Comment by Aupajo** [comment]
@hansfpc Here's what worked for me:

1. Open `nshift.xcodeproject`
2. Run Build (⌘B)
3. Open a terminal
3. Copy the compiled binary to your `/usr/local/bin` directory: `cp ~/Library/Developer/Xcode/DerivedData/nshift-*/Build/Products/Debug/nshift /usr/local/bin/`
4. Set the executable bit on the binary file: `chmod u+x /usr/local/bin/nshift`
